### ISSUE TITLE
FetchError: request to http://localhost:1880/coco/model.json

### ISSUE THREAD

**Issue by RitaSghe** [dceejay/tfjs-coco-ssd#17]
Update to 1.0.1 version and now I have this error and object detection don't work ...
I have this error on my pc (the previous error is on my Raspberry)

Pc
SO - ubuntu 20.04 
Node-RED version: v2.0.6
Node.js  version: v14.16.0

I have this error because when I installed node red I switched the port that is not 1880.
If I change the port in 1880 the node works fine ....
Well, where I can change the path to set my port?

**Comment by dceejay** [comment]
Does this replace #16 ? If so can we close that ?

**Comment by RitaSghe** [comment]
No, no, because the n. 16 is an error on my Raspberry and n. 17 is an error on my pc ubuntu,
Both with node red but two different project ....

**Comment by dceejay** [comment]
How did you switch the port ? The node reads the value from the settings file uiPort variable so it should use that.

**Comment by RitaSghe** [comment]
Changing uiPort teh value.
I imagine the node reads the value from the settings file uiPort variable, but this is my situation ...

![ddddd](https://user-images.githubusercontent.com/81916825/144015350-606d290f-7722-44ae-a8e3-35e9bfe56e63.png)
..

**Comment by dceejay** [comment]
Version v1.0.2 published to fix this
