### ISSUE TITLE
Installing it using Docker Node-RED doesn't work

### ISSUE THREAD

**Issue by bonastreyair** [dceejay/tfjs-coco-ssd#2]
I'm using `Node-RED v1.0.4` on `Docker` on the latest MacBook Pro 13'' hardware in MacOS Catalina.

Whenever I put the node in any flow, an error appears like this:
<img width="665" alt="Screenshot 2020-04-02 at 13 25 24" src="https://user-images.githubusercontent.com/37800834/78244207-6e97db00-74e5-11ea-97ad-50fa3c90cb12.png">
> Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /data/node_modules/@tensorflow/tfjs-node/lib/napi-v5/../../deps/lib/libtensorflow.so.1)

How can I handle this issue to make it work? It is like `tensorflow.js` has not been installed, right?
Or is it because the `Node-RED Docker Image` is based on an unsupported `Linux` for `tensorflow.js`?

Thanks,

**Comment by dceejay** [comment]
Correct - the Alpine linux support has an issue open against it 
https://github.com/tensorflow/tfjs/issues/1425

**Comment by bonastreyair** [comment]
While we wait until `tensorflow` or `Alpine Linux` fixes this issue, I wanted to share with you the new node I created, inspired and learnt a lot from your repo, it would mean a lot to me if you could check it out.
- [node-red-contrib-teachable-machine](https://flows.nodered.org/node/node-red-contrib-teachable-machine)

It is functional but it lacks of good documentation I will keep posting updates to make it more clear in the README file.

I have another node of an additional node for standard pretrained Mobilenets Classification, I'm on testing now and it works great. If you want I could make a PR, I would just need to integrate the node in your package, so that this package would contain detection and classification nodes. What do you think?

Thanks! You inspired me!

**Comment by dceejay** [comment]
Hi - I also have this repo I did share (sort of) https://github.com/dceejay/tfjs-nodes
which has nodes for predict and posenet. Is your other node like the predict one ? or another variant ? I decided to release them separately as things like the model in this are somewhat large for users who don't want to use it - so I thought keeping them separate may be a good idea.

So what does you new node do ? how does it fit in (sorry for asking dumb questions)

**Comment by dceejay** [comment]
Aha - just install your teachable node - and found the link to https://teachablemachine.withgoogle.com/ - awesome stuff...

**Comment by bonastreyair** [comment]
Oh I see, you made a standard `tf.model()` to later do `model.predict()`. I made a new node using the specific implementation of [tfjs-model/mobilenets](https://www.npmjs.com/package/@tensorflow-models/mobilenet), it is more similar to the coco ssd you made, where the model has its own model implementation made by tensorflow. My node just wanted to be used for this model pretrained.

My idea was just a node that drags and drops and gives you the basic mobilenets (just like ssd coco).

I was writing this down when you posted the link to [teachable machine](https://teachablemachine.withgoogle.com/). Yeah! The thing is that you can train on the web browser your model, uploaded directly and use that URL and paste into the new [node-red-contrib-teachable-machine](https://github.com/bonastreyair/node-red-contrib-teachable-machine) node and you have the results all made in local without HTML.

**Comment by dceejay** [comment]
Hi 

I'm fine with you doing a mobilenet version standalone if you wish ? If you copy the naming style they may look "joined up" :-) 

Re Thinking machine - yes - really neat - am on the right page now I found the link... of course now I need to sort out my pi camera and see if it can run the model I trained on the mac :-)

**Comment by bonastreyair** [comment]
Yeah maybe I could pack everything together within the [tfjs-node repo](https://github.com/dceejay/tfjs-nodes), that's what you mean right?

I will make a PR and you can check it out.

**Comment by jschaeke** [comment]
Any update regarding this issue as https://github.com/tensorflow/tfjs/issues/1425 has been closed without solution?

**Comment by dceejay** [comment]
Our docker project does have an option for you to build custom build based on debian instead that may work as it uses the more standard libraries. But otherwise no - it's for tfjs to fix under alpine or not.

**Comment by tve** [comment]
I just tried using the debian docker image (built with node v12 and NR 1.3.5) and I get an Illegal Instruction (core dumped).
STR:
- build docker image on x64 linux using docker-debian.sh script (https://github.com/node-red/node-red-docker/blob/master/docker-custom/docker-debian.sh)
- launch docker container without any volume mapped to /data
- open admin UI, use palette manager to install node-red-contrib-tfjs-coco
- drag tfjs-coco node into flow, deploy
- NR will crash
- log:
```
> node-red-docker@1.3.5 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"

1 Jul 02:52:20 - [info]

Welcome to Node-RED
===================

1 Jul 02:52:20 - [info] Node-RED version: v1.3.5
1 Jul 02:52:20 - [info] Node.js  version: v12.22.1
1 Jul 02:52:20 - [info] Linux 5.4.0-77-generic x64 LE
1 Jul 02:52:21 - [info] Loading palette nodes
1 Jul 02:52:21 - [info] Settings file  : /data/settings.js
1 Jul 02:52:21 - [info] Context store  : 'default' [module=memory]
1 Jul 02:52:21 - [info] User directory : /data
1 Jul 02:52:21 - [warn] Projects disabled : editorTheme.projects.enabled=false
1 Jul 02:52:21 - [info] Flows file     : /data/flows.json
1 Jul 02:52:21 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
[...]
---------------------------------------------------------------------
1 Jul 02:52:21 - [info] Server now running at http://127.0.0.1:1880/
1 Jul 02:52:21 - [info] Starting flows
1 Jul 02:52:21 - [info] Started flows
1 Jul 02:53:16 - [info] Installing module: node-red-contrib-tfjs-coco-ssd, version: 0.5.6
1 Jul 02:53:43 - [info] Installed module: node-red-contrib-tfjs-coco-ssd
1 Jul 02:53:43 - [info] Added node types:
1 Jul 02:53:43 - [info]  - node-red-contrib-tfjs-coco-ssd:tensorflowCoco
1 Jul 02:54:01 - [info] Stopping flows
1 Jul 02:54:01 - [info] Stopped flows
1 Jul 02:54:01 - [info] Starting flows
Illegal instruction (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! node-red-docker@1.3.5 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 132
```

If someone has managed to run this puppy under docker I'd love to hear!

**Comment by regystro** [comment]
> Our docker project does have an option for you to build custom build based on debian instead that may work as it uses the more standard libraries. But otherwise no - it's for tfjs to fix under alpine or not.

Sorry but where can we find that docker project? Thank you.

**Comment by twocolors** [comment]
build [docker](https://github.com/twocolors/node-red-docker) based debian for support tensorflow

**Comment by MeycemMariem** [comment]
Exactly the "problem" is that the Tensorflow.js is dependent of the system library **glibc**, and the official node-red image uses the Alpine Linux distribution which uses the **musl** library which causes the error reported by the node. To be able to resolve this you have to create your own node-red container (do not use the official image).

The best way I have found to do so is to build it on top of a Node.js image (eventually using Debian) below you can find the Dockerfile. (Note that the Node .js version should be equal or greater than the version 14 as node-red requires so)

```Dockerfile
FROM node:14
# Set the timezone (replace with your timezone)
ENV TZ=Your/Timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN npm install -g --unsafe-perm node-red
EXPOSE 1880
CMD ["node-red"]
```

**Comment by bonastreyair** [comment]
you can also use a debian version of node-red they offer official ones, no need to create your own :)
