### ISSUE TITLE
Error: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by ghost** [dceejay/tfjs-coco-ssd#20]
Today I update to the 1.0.3 version and now I have this error:
Error: /home/pi/.node-red/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node: wrong ELF class: ELFCLASS64

node red 2.1.6
node js 12.22.0
Raspberry pi4 - OS raspberry

**Comment by crxporter** [comment]
I've got the same issue as you. I'm running nodered 2.2.2, node.js 16.x, and raspberry pi os bullseye 32 bits version. Nothing else running on the pi, I just now installed everything fresh and tried this node.

I last had this setup working using this same pi but it was running buster.

**Comment by crxporter** [comment]
I "downgraded" to buster and got the same issue.

The fix you mentioned in this comment https://github.com/dceejay/tfjs-coco-ssd/issues/22#issuecomment-1128811697 seems to be working. (node 16.15.0, nr 2.2.2, buster 32 bit)

For those who don't want to click but do want to fix this - after installing the node on 32 bit nodered - go to the terminal in your `~/.node-red/` directory and run:
```
npm rebuild @tensorflow/tfjs-node --build-from-source
```

Testing this fix on bullseye now. Will edit this comment if the same fix works on Bullseye 32 bit.

**Comment by dceejay** [comment]
Thanks for identifying the work around/fix
