### ISSUE TITLE
Cannot Install package

### ISSUE THREAD

**Issue by henjoe** [dceejay/tfjs-coco-ssd#28]
Hello, when I tried to install the package either via CLI or package manager (via nodered UI), it gives me the ff error:

![image](https://github.com/dceejay/tfjs-coco-ssd/assets/49782655/5343621b-d6a6-48a1-ac45-1caec91ba1e7)

Here is my environment:
OS: Windows 10 
Nodered V2.x
NodeJS V18.x

**Comment by dceejay** [comment]
None of those are errors - only warnings... 
I see you also opened a discussion on the forum so I will close this until there is an actual issue to fix.
